### ISSUE TITLE
"An argument" description for some commands

### ISSUE THREAD

**Issue by FerPerales** [ediardo/kmdr-cli#11]
I think this happens when the command is not recognize, but not sure.

How to reproduce

Try, for example, `ansible`

**Comment by ediardo** [comment]
Hi @FerPerales , thanks for reporting this.

You assumed right. This message is displayed when the client doesn't find a match for the program you just queried. The message could be improved in order to tell the user that the program `ansible` is not supported yet. I'll definitely keep `ansible` under the radar and try to integrate it soon. 

You can check the list of supported programs here https://github.com/ediardo/kmdr.sh#supported-programs. Let me know if you think of more programs we should support as it helps us to focus on important use cases.

**Comment by ediardo** [comment]
It will be fixed in v.0.2 #21

**Comment by FerPerales** [comment]
Superb. Waiting for it.
